---
title: "Acta reunión grupo de trabajo"
format: html
---

A las 15:30 del 4 de septiembre de 2026, se reúne el Grupo de Trabajo de Software de la Sociedad de Estadística e Investigación Operativa de la Sociedad de Estadística, Investigación Operativa y Ciencia de Datos en el aula 23 de la Facultad de Ciencias Económicas y Empresariales de la Universidade de Santiago de Compostela.

Preside la reunión el coordinador Emilio López Cano, de la Universidad Rey Juan Carlos.

Asistentes:

* Emilio López Cano (coordinador)
* Nora Martínez Villanueva
* Marta Sestelo Pérez
* Óscar Soto Sánchez
* Natalia Madrueño Sierro
* Carmen Lancho Martín
* María Escorihuela Sahún
* Emilio Torres Manzanera (invitado)

La reunión se convoca en el marco del XLII Congreso Nacional de Estadística, Investigación Operativa y Ciencia de Datos, sin un orden del día establecido.


## Asuntos tratados

El coordinador del grupo realiza una presentación que se puede consultar en el [repositorio reuniones](https://github.com/soceio/reuniones) de la [organización](https://github.com/soceio) de GitHub del grupo en el siguiente enlace: <https://soceio.github.io/reuniones/2026/presentacion.html>

### Sesiones del grupo en SEIO 2026

Se han organizado tres sesiones del grupo de trabajo con trabajos muy interesantes:

* Sesión 1: Paquetes. Ricardo - PEAXAY; Inés - neuralGAM; Nataly - dimControl; Nora - clustcif.

* Sesión 2: Aplicaciones. Salva - TTS - MNAT; Emilio - Natación; Sergio - Corr. - Imp.; Luis Mariano - TSP - genéticos

* Sesión 3: ML & IA. Natalia - NLP - genAI; María - PowerBI+; Carmen - Complexity; Pablo - Clasif. - plagas

Se recuerda en este punto que el grupo de trabajo tiene un repositorio de presentaciones en GitHub, y se anima a los miembros a **subir sus presentaciones** allí para que estén disponibles para todos, tanto de este congreso como de los anteriores. Todos los miembros que han comunicado su usuario de GitHub han sido añadidos a la organización del grupo, si todavía no lo has hecho, envíaselo al coordinador. Quien no se encuentre cómodo con GitHub, puede enviar su presentación al coordinador para que la suba él.

### Miembros del grupo de trabajo

A febrero de 2026, última actualización recibida, éramos 65 miembros de los cuales 18 estudiantes.

El coordinador comenta que en las reuniones le gustaría reconocer los logros de los miembros del grupo. Se solicita que los miembros que tengan algo que compartir, lo comuniquen al coordinador antes de la próxima reunión. En esta ocasión, se reconoce el logro de **Alberto Torrejón**, que ha conseguido plaza en la Universidad de Economía y Empresa de Viena, sede de la _R Foundation_, donde va a trabajar con Kurt Hornik, vicepresidente de la R Foundation y uno de los principales contribuyentes de R.

### Ayuda a grupos y memoria

La ayuda recibida en la última convocatoria se ha aplicado íntegramente a la ayuda a estudiantes para los congresos de Lleida y Santiago. Para el próximo año se puede organizar un seminario, o co-organizar congreso de R, o ambas cosas. Nos pedirán la memoria anual enseguida, y se abrirá la convocatoria para la ayuda a grupos de trabajo para los próximos dos años.

Para esta convocatoria se propone **organizar el segundo seminario del grupo de trabajo en 2027**. Se solicitan voluntarios para la organización del mismo. Marta y Nora se ofrecen para el siguiente (2029) en Vigo, ya que se han incorporado recientemente al grupo. Si no hay voluntarios para 2027, se puede organizar en la Universidad Rey Juan Carlos como el primero ([Vídeo](https://tv.urjc.es/video/668c231043c849696e1eef63)), pero sería mejor no repetir.

NOTA: Por si ayuda, al final del acta se incluye una tabla de frecuencias de los miembros del grupo de trabajo según el dominio de su correo (no tengo otra información aunque la recopilaré para la web del grupo). Gracias por la sugerencia Nora.


### Otras tareas del grupo de trabajo

Aparte de mantener el Repositorio presentaciones, es urgente que alguien se ocupe de llenar de contenido la págna web del grupo. Carmen sugiere que se puede realizar como trabajo de fin de grado de algún estudiante. El coordinador no se opone, pero tiene que ser algo "mantebible" en el tiempo. Actualmente hay un "esqueleto" en formato [quarto website](https://quarto.org/docs/websites/). El repositorio es el siguiente: <https://github.com/soceio/website>

También hay que mantener la lista de distribución, actualmente [un grupo de Google](https://groups.google.com/g/soceio). Es un proceso tedioso por las altas y bajas, si alguien tiene una idea de cómo hacerlo mejor y más más automático se agradecería.

Hay que dar visibilidad en [la web de la SEIO](https://www.seio.es/grupos-de-trabajo/) y otros sitios al grupo de trabajo. Actualmente aparece muy poca información, se apliará y sobre todo cuando haya contenido en la web se pondrá ahí también.



### Próximos eventos

El coordinador informa de dos próximos eventos relevantes para el grupo, y anima a los miembros a participar en ellos:

* [V Congreso y XVI Jornadas de Usuarios de R 2026](https://eventos.ull.es/152998/detail/v-congreso-y-xvi-jornadas-de-usuarios-de-r-2026.html). San Cristóbal de La Laguna – Tenerife
25, 26 y 27 de noviembre de 2026

* [Laboratorio de Ciencia de Datos: Presentación libro «Advanced Basketball Data Science» y 105ª reunión de usuarios R](https://eventos.urjc.es/157815/)


### Lo que viene

El coordinador comenta sobre una cuestión que puede ser relevante en los próximos años en relación a la actividad del grupo. Está ganando atención no solo a nivel académico sino también instituciona y empresarial. En general, la Unión Europea va a invertir en tecnologías cuánticas. En particular, la Ciencia de Datos Cuántica (Quantum Data Science) es un área emergente que combina la computación cuántica con la ciencia de datos. Se comparten estos tres enlaces relevantes para quien quiera profundizar en el tema:

* [Quantum Data Science search](https://share.google/WMboRJBLY6IxNhcp9)

* [Quantum Data Scientist: The New Role of the 21st Century](https://www.computer.org/publications/tech-news/trends/quantum-data-scientist)

* [EU Funding Opportunities Across the Quantum Technology Spectrum](https://nordicinnovators.com/industries/quantum-technologies/)

Entre los asistentes a la reunión en general es todavía muy desconocido, aunque en la Universidad de Vigo hay algún grupo haciendo algo. Se propone que dentro de la actividad del grupo organicemos algún _webinar_ sobre el tema para ver cómo podemos aprovechar esta nueva ola desde nuestra actividad. 


### Coordinación

Debemos ir pensando en el relevo de la coordinación según [normativa](https://www.seio.es/grupos-de-trabajo/). Aunque según la normativa el cambio ya se debería haber hecho (máximo 3 años), el coordinador no tiene problema en continuar hasta el próximo congreso en que se elija un nuevo coordinador (o coordinadora). Lo podemos hacer parecido a como se hace en la SEIO, quedando el "saliente" un periodo colaborando con el entrante.

En este punto el coordinador agradece a Carmen Lancho la ayuda en la coordinación del grupo en los dos últimos congresos, porque sin su ayuda no hubiera sido posible organizar las sesiones del grupo de trabajo y sobre todo gestionar la ayuda a los estudiantes del grupo.

## Conclusiones

* Se necesitan voluntarios para la organización del II Seminario SOCEIO, que se celebrará en 2027. 

* Se necesitan voluntarios para llenar de contenido la página web del grupo, que está hecha en quarto (se puede proponer otro sistema que sea "mantenible")

* Se solicita que los miembros que tengan logros que compartir, lo comuniquen al coordinador antes de la próxima reunión.

* Se solicita que si algún miembro conoce algún grupo de investigación o empresa que esté haciendo algo en Quantum Data Science, lo comunique al coordinador para poder organizar un _webinar_ sobre el tema.

* Para el siguiente congreso hay que proponer un cambio de coordinador según la normativa. Trabajaré en ello.


## Anexo: ¿De dónde venimos?

NOTA: la tabla está generada con la lista de miembros más reciente que tenemos, que es de septiembre de 2026. 

```{r}
#| echo: false
#| message: false
library(readxl)
library(dplyr)
library(stringr)

archivo_reciente <- "../datos/protegidos/2026-09_GT_Software.xlsx"

crudo <- read_excel(archivo_reciente, col_names = FALSE)
fila_cabecera <- which(crudo[[1]] == "Núm. asoc.")[1]

miembros <- read_excel(archivo_reciente, skip = fila_cabecera - 1)


miembros |>
  mutate(dominio = str_to_lower(sub("^.*@", "", `Email principal`))) |>
  count(dominio, sort = TRUE, name = "Frecuencia") |>
  rename(Dominio = dominio) |> 
    knitr::kable(caption = "Tabla de frecuencias de miembros del grupo de trabajo según dominio de correo electrónico")
```