---
title: "Reunión grupo de trabajo software"
date: 2026-09-04
format: 
    revealjs:
        theme: solarized
        transition: slide
---


## Agenda

* Sesiones SEIO

* Miembros del grupo

* Próximos eventos

* Lo que viene



## Sesiones


::: {.columns}

::: {.column width="33%"}

### Paquetes

- Ricardo - PEAXAY
- Inés - neuralGAM
- Nataly - dimControl
- Nora - clustcif


:::

::: {.column width="33%"}

### Aplicaciones

- Salva - TTS - MNAT
- Emilio - Natación
- Sergio - Corr. - Imp.
- Luis Mariano - TSP - genéticos


:::

::: {.column width="33%"}

### ML & IA

- Natalia - NLP - genAI
- María - PowerBI+
- Carmen - Complexity
- Pablo - Clasif. - plagas

:::

:::




## Miembros

### A febrero de 2026

* 65 miembros

* 18 estudiantes

## Reconocimientos

* **Alberto Torrejón**: Ha conseguido plaza en la Universidad de Economía y Empresa de Viena, sede de la _R Foundation_, donde va a trabajar con Kurt Hornik, vicepresidente de la R Foundation y uno de los principales contribuyentes de R. 

## Ayuda a grupos y memoria

* Aplicada íntegramente a la ayuda a estudiantes

* Para el próximo año se puede organizar un seminario, o co-organizar congreso de R.

* Nos pedirán la memoria anual enseguida

## Tareas

* Repositorio presentaciones | [Organización GitHub](https://github.com/soceio)

* Págna web del grupo

* Lista de distribución

* Visibilidad en SEIO y otros sitios

* Organización II Seminario SOCEIO


## Próximos eventos

* [V Congreso y XVI Jornadas de Usuarios de R 2026](https://eventos.ull.es/152998/detail/v-congreso-y-xvi-jornadas-de-usuarios-de-r-2026.html). San Cristóbal de La Laguna – Tenerife
25, 26 y 27 de noviembre de 2026

* [Laboratorio de Ciencia de Datos: Presentación libro «Advanced Basketball Data Science» y 105ª reunión de usuarios R](https://eventos.urjc.es/157815/)


# Lo que viene

## Quantum Data Science

* [Quantum Data Science search](https://share.google/WMboRJBLY6IxNhcp9)

* [Quantum Data Scientist: The New Role of the 21st Century](https://www.computer.org/publications/tech-news/trends/quantum-data-scientist)

* [EU Funding Opportunities Across the Quantum Technology Spectrum](https://nordicinnovators.com/industries/quantum-technologies/)


## Debate

* Sugerencias

* Voluntari@s

* Próximo relevo según [normativa](https://www.seio.es/grupos-de-trabajo/) 
